!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!  This file is AUTOMATICALLY GENERATED by:
!!  ../tools/fortran_wrappers.pl ../include/magma_d.i
!!  Do not edit.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

module magma_dfortran

use magma_param

implicit none

!---- Fortran interfaces to MAGMA subroutines ----
interface

integer function magmaf_get_dpotrf_nb( m )
    integer :: m
end function magmaf_get_dpotrf_nb

integer function magmaf_get_dgetrf_nb( m )
    integer :: m
end function magmaf_get_dgetrf_nb

integer function magmaf_get_dgetri_nb( m )
    integer :: m
end function magmaf_get_dgetri_nb

integer function magmaf_get_dgeqrf_nb( m )
    integer :: m
end function magmaf_get_dgeqrf_nb

integer function magmaf_get_dgeqlf_nb( m )
    integer :: m
end function magmaf_get_dgeqlf_nb

integer function magmaf_get_dgehrd_nb( m )
    integer :: m
end function magmaf_get_dgehrd_nb

integer function magmaf_get_dsytrd_nb( m )
    integer :: m
end function magmaf_get_dsytrd_nb

integer function magmaf_get_dgelqf_nb( m )
    integer :: m
end function magmaf_get_dgelqf_nb

integer function magmaf_get_dgebrd_nb( m )
    integer :: m
end function magmaf_get_dgebrd_nb

integer function magmaf_get_dsygst_nb( m )
    integer :: m
end function magmaf_get_dsygst_nb

integer function magmaf_get_dgesvd_nb( m )
    integer :: m
end function magmaf_get_dgesvd_nb

subroutine magmaf_dgebrd( m, n, a, lda, d, e, tauq, taup, work, lwork, info, queue )
    integer          :: m
    integer          :: n
    double precision :: a(*)
    integer          :: lda
    double precision :: d(*)
    double precision :: e(*)
    double precision :: tauq(*)
    double precision :: taup(*)
    double precision :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_dgebrd

subroutine magmaf_dgeqrf( m, n, A, lda, tau, work, lwork, info, queue )
    integer          :: m
    integer          :: n
    double precision :: A(*)
    integer          :: lda
    double precision :: tau(*)
    double precision :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_dgeqrf

subroutine magmaf_dgesv( n, nrhs, A, lda, ipiv, B, ldb, info, queue )
    integer          :: n
    integer          :: nrhs
    double precision :: A(*)
    integer          :: lda
    integer          :: ipiv(*)
    double precision :: B(*)
    integer          :: ldb
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_dgesv

subroutine magmaf_dgetrf( m, n, A, lda, ipiv, info, queue )
    integer          :: m
    integer          :: n
    double precision :: A(*)
    integer          :: lda
    integer          :: ipiv(*)
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_dgetrf

subroutine magmaf_dposv( uplo, n, nrhs, A, lda, B, ldb, info, queue )
    character        :: uplo
    integer          :: n
    integer          :: nrhs
    double precision :: A(*)
    integer          :: lda
    double precision :: B(*)
    integer          :: ldb
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_dposv

subroutine magmaf_dpotrf( uplo, n, A, lda, info, queue )
    character        :: uplo
    integer          :: n
    double precision :: A(*)
    integer          :: lda
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_dpotrf

subroutine magmaf_dorghr( n, ilo, ihi, a, lda, tau, dT, dT_offset, nb, info, queue )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    double precision :: a(*)
    integer          :: lda
    double precision :: tau(*)
    magma_devptr_t :: dT
    integer          :: dT_offset
    integer          :: nb
    integer          :: info
    integer          :: queue
end subroutine magmaf_dorghr

subroutine magmaf_dorgqr( m, n, k, a, lda, tau, dT, dT_offset, nb, info, queue )
    integer          :: m
    integer          :: n
    integer          :: k
    double precision :: a(*)
    integer          :: lda
    double precision :: tau(*)
    magma_devptr_t :: dT
    integer          :: dT_offset
    integer          :: nb
    integer          :: info
    integer          :: queue
end subroutine magmaf_dorgqr

subroutine magmaf_dormtr( side, uplo, trans, m, n, a, lda, tau, c, ldc, work, lwork,  &
        info, queue )
    character        :: side
    character        :: uplo
    character        :: trans
    integer          :: m
    integer          :: n
    double precision :: a(*)
    integer          :: lda
    double precision :: tau(*)
    double precision :: c(*)
    integer          :: ldc
    double precision :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_dormtr

subroutine magmaf_dormqr( side, trans, m, n, k, a, lda, tau, c, ldc, work, lwork, info,  &
        queue )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    double precision :: a(*)
    integer          :: lda
    double precision :: tau(*)
    double precision :: c(*)
    integer          :: ldc
    double precision :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_dormqr

subroutine magmaf_dormql( side, trans, m, n, k, a, lda, tau, c, ldc, work, lwork, info,  &
        queue )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    double precision :: a(*)
    integer          :: lda
    double precision :: tau(*)
    double precision :: c(*)
    integer          :: ldc
    double precision :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_dormql

subroutine magmaf_dgeev( jobvl, jobvr, n, a, lda, WR, WI, vl, ldvl, vr, ldvr, work,  &
        lwork, info, queue )
    character        :: jobvl
    character        :: jobvr
    integer          :: n
    double precision :: a(*)
    integer          :: lda
    double precision :: WR(*)
    double precision :: WI(*)
    double precision :: vl(*)
    integer          :: ldvl
    double precision :: vr(*)
    integer          :: ldvr
    double precision :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_dgeev

subroutine magmaf_dgesvd( jobu, jobvt, m, n, a, lda, s, u, ldu, vt, ldvt, work, lwork,  &
        info, queue )
    character        :: jobu
    character        :: jobvt
    integer          :: m
    integer          :: n
    double precision :: a(*)
    integer          :: lda
    double precision :: s(*)
    double precision :: u(*)
    integer          :: ldu
    double precision :: vt(*)
    integer          :: ldvt
    double precision :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_dgesvd

subroutine magmaf_dsyevd( jobz, uplo, n, a, lda, w, work, lwork, iwork, liwork, info,  &
        queue )
    character        :: jobz
    character        :: uplo
    integer          :: n
    double precision :: a(*)
    integer          :: lda
    double precision :: w(*)
    double precision :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_dsyevd

subroutine magmaf_dstedx( range, n, vl, vu, il, iu, d, e, z, ldz, rwork, lrwork, iwork,  &
        liwork, dwork, info, queue )
    character        :: range
    integer          :: n
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    double precision :: d(*)
    double precision :: e(*)
    double precision :: z(*)
    integer          :: ldz
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    magma_devptr_t :: dwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_dstedx

subroutine magmaf_dgehrd( n, ilo, ihi, a, lda, tau, work, lwork, dT, dT_offset, info,  &
        queue )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    double precision :: a(*)
    integer          :: lda
    double precision :: tau(*)
    double precision :: work(*)
    integer          :: lwork
    magma_devptr_t :: dT
    integer          :: dT_offset
    integer          :: info
    integer          :: queue
end subroutine magmaf_dgehrd

subroutine magmaf_dsytrd( uplo, n, a, lda, d, e, tau, work, lwork, info, queue )
    character        :: uplo
    integer          :: n
    double precision :: a(*)
    integer          :: lda
    double precision :: d(*)
    double precision :: e(*)
    double precision :: tau(*)
    double precision :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_dsytrd

subroutine magmaf_dprint( m, n, A, lda )
    integer          :: m
    integer          :: n
    double precision :: A(*)
    integer          :: lda
end subroutine magmaf_dprint

end interface

!---- Fortran-only subroutines (see ../tools/fortran_wrappers.pl to edit) ----
contains

subroutine magmaf_doff1d( ptrNew, ptrOld, inc, i)
    magma_devptr_t   :: ptrNew
    magma_devptr_t   :: ptrOld
    integer          :: inc, i

    ptrNew = ptrOld + (i-1) * inc * sizeof_double
end subroutine magmaf_doff1d

subroutine magmaf_doff2d( ptrNew, ptrOld, lda, i, j)
    magma_devptr_t   :: ptrNew
    magma_devptr_t   :: ptrOld
    integer          :: lda, i, j

    ptrNew = ptrOld + ((j-1) * lda + (i-1)) * sizeof_double
end subroutine magmaf_doff2d

end module magma_dfortran
