!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!  This file is AUTOMATICALLY GENERATED by:
!!  ../tools/fortran_wrappers.pl ../include/magma_c.i
!!  Do not edit.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

module magma_cfortran

use magma_param

implicit none

!---- Fortran interfaces to MAGMA subroutines ----
interface

integer function magmaf_get_cpotrf_nb( m )
    integer :: m
end function magmaf_get_cpotrf_nb

integer function magmaf_get_cgetrf_nb( m )
    integer :: m
end function magmaf_get_cgetrf_nb

integer function magmaf_get_cgetri_nb( m )
    integer :: m
end function magmaf_get_cgetri_nb

integer function magmaf_get_cgeqrf_nb( m )
    integer :: m
end function magmaf_get_cgeqrf_nb

integer function magmaf_get_cgeqlf_nb( m )
    integer :: m
end function magmaf_get_cgeqlf_nb

integer function magmaf_get_cgehrd_nb( m )
    integer :: m
end function magmaf_get_cgehrd_nb

integer function magmaf_get_chetrd_nb( m )
    integer :: m
end function magmaf_get_chetrd_nb

integer function magmaf_get_cgelqf_nb( m )
    integer :: m
end function magmaf_get_cgelqf_nb

integer function magmaf_get_cgebrd_nb( m )
    integer :: m
end function magmaf_get_cgebrd_nb

integer function magmaf_get_chegst_nb( m )
    integer :: m
end function magmaf_get_chegst_nb

integer function magmaf_get_cgesvd_nb( m )
    integer :: m
end function magmaf_get_cgesvd_nb

subroutine magmaf_cgebrd( m, n, a, lda, d, e, tauq, taup, work, lwork, info, queue )
    integer          :: m
    integer          :: n
    complex          :: a(*)
    integer          :: lda
    real             :: d(*)
    real             :: e(*)
    complex          :: tauq(*)
    complex          :: taup(*)
    complex          :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_cgebrd

subroutine magmaf_cgeqrf( m, n, A, lda, tau, work, lwork, info, queue )
    integer          :: m
    integer          :: n
    complex          :: A(*)
    integer          :: lda
    complex          :: tau(*)
    complex          :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_cgeqrf

subroutine magmaf_cgesv( n, nrhs, A, lda, ipiv, B, ldb, info, queue )
    integer          :: n
    integer          :: nrhs
    complex          :: A(*)
    integer          :: lda
    integer          :: ipiv(*)
    complex          :: B(*)
    integer          :: ldb
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_cgesv

subroutine magmaf_cgetrf( m, n, A, lda, ipiv, info, queue )
    integer          :: m
    integer          :: n
    complex          :: A(*)
    integer          :: lda
    integer          :: ipiv(*)
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_cgetrf

subroutine magmaf_cposv( uplo, n, nrhs, A, lda, B, ldb, info, queue )
    character        :: uplo
    integer          :: n
    integer          :: nrhs
    complex          :: A(*)
    integer          :: lda
    complex          :: B(*)
    integer          :: ldb
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_cposv

subroutine magmaf_cpotrf( uplo, n, A, lda, info, queue )
    character        :: uplo
    integer          :: n
    complex          :: A(*)
    integer          :: lda
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_cpotrf

subroutine magmaf_cunghr( n, ilo, ihi, a, lda, tau, dT, dT_offset, nb, info, queue )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    complex          :: a(*)
    integer          :: lda
    complex          :: tau(*)
    magma_devptr_t :: dT
    integer          :: dT_offset
    integer          :: nb
    integer          :: info
    integer          :: queue
end subroutine magmaf_cunghr

subroutine magmaf_cungqr( m, n, k, a, lda, tau, dT, dT_offset, nb, info, queue )
    integer          :: m
    integer          :: n
    integer          :: k
    complex          :: a(*)
    integer          :: lda
    complex          :: tau(*)
    magma_devptr_t :: dT
    integer          :: dT_offset
    integer          :: nb
    integer          :: info
    integer          :: queue
end subroutine magmaf_cungqr

subroutine magmaf_cunmtr( side, uplo, trans, m, n, a, lda, tau, c, ldc, work, lwork,  &
        info, queue )
    character        :: side
    character        :: uplo
    character        :: trans
    integer          :: m
    integer          :: n
    complex          :: a(*)
    integer          :: lda
    complex          :: tau(*)
    complex          :: c(*)
    integer          :: ldc
    complex          :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_cunmtr

subroutine magmaf_cunmqr( side, trans, m, n, k, a, lda, tau, c, ldc, work, lwork, info,  &
        queue )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    complex          :: a(*)
    integer          :: lda
    complex          :: tau(*)
    complex          :: c(*)
    integer          :: ldc
    complex          :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_cunmqr

subroutine magmaf_cunmql( side, trans, m, n, k, a, lda, tau, c, ldc, work, lwork, info,  &
        queue )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    complex          :: a(*)
    integer          :: lda
    complex          :: tau(*)
    complex          :: c(*)
    integer          :: ldc
    complex          :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_cunmql

subroutine magmaf_cgeev( jobvl, jobvr, n, a, lda, geev_w_array, vl, ldvl, vr, ldvr, work,  &
        lwork, rwork, info, queue )
    character        :: jobvl
    character        :: jobvr
    integer          :: n
    complex          :: a(*)
    integer          :: lda
    complex          :: geev_w_array(*)
    complex          :: vl(*)
    integer          :: ldvl
    complex          :: vr(*)
    integer          :: ldvr
    complex          :: work(*)
    integer          :: lwork
    real             :: rwork(*)
    integer          :: info
    integer          :: queue
end subroutine magmaf_cgeev

subroutine magmaf_cgesvd( jobu, jobvt, m, n, a, lda, s, u, ldu, vt, ldvt, work, lwork,  &
        rwork, info, queue )
    character        :: jobu
    character        :: jobvt
    integer          :: m
    integer          :: n
    complex          :: a(*)
    integer          :: lda
    real             :: s(*)
    complex          :: u(*)
    integer          :: ldu
    complex          :: vt(*)
    integer          :: ldvt
    complex          :: work(*)
    integer          :: lwork
    real             :: rwork(*)
    integer          :: info
    integer          :: queue
end subroutine magmaf_cgesvd

subroutine magmaf_cheevd( jobz, uplo, n, a, lda, w, work, lwork, rwork, lrwork, iwork,  &
        liwork, info, queue )
    character        :: jobz
    character        :: uplo
    integer          :: n
    complex          :: a(*)
    integer          :: lda
    real             :: w(*)
    complex          :: work(*)
    integer          :: lwork
    real             :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_cheevd

subroutine magmaf_cstedx( range, n, vl, vu, il, iu, d, e, z, ldz, rwork, lrwork, iwork,  &
        liwork, dwork, info, queue )
    character        :: range
    integer          :: n
    real             :: vl
    real             :: vu
    integer          :: il
    integer          :: iu
    real             :: d(*)
    real             :: e(*)
    complex          :: z(*)
    integer          :: ldz
    real             :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    magma_devptr_t :: dwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_cstedx

subroutine magmaf_cgehrd( n, ilo, ihi, a, lda, tau, work, lwork, dT, dT_offset, info,  &
        queue )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    complex          :: a(*)
    integer          :: lda
    complex          :: tau(*)
    complex          :: work(*)
    integer          :: lwork
    magma_devptr_t :: dT
    integer          :: dT_offset
    integer          :: info
    integer          :: queue
end subroutine magmaf_cgehrd

subroutine magmaf_chetrd( uplo, n, a, lda, d, e, tau, work, lwork, info, queue )
    character        :: uplo
    integer          :: n
    complex          :: a(*)
    integer          :: lda
    real             :: d(*)
    real             :: e(*)
    complex          :: tau(*)
    complex          :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_chetrd

subroutine magmaf_cprint( m, n, A, lda )
    integer          :: m
    integer          :: n
    complex          :: A(*)
    integer          :: lda
end subroutine magmaf_cprint

end interface

!---- Fortran-only subroutines (see ../tools/fortran_wrappers.pl to edit) ----
contains

subroutine magmaf_coff1d( ptrNew, ptrOld, inc, i)
    magma_devptr_t   :: ptrNew
    magma_devptr_t   :: ptrOld
    integer          :: inc, i

    ptrNew = ptrOld + (i-1) * inc * sizeof_complex
end subroutine magmaf_coff1d

subroutine magmaf_coff2d( ptrNew, ptrOld, lda, i, j)
    magma_devptr_t   :: ptrNew
    magma_devptr_t   :: ptrOld
    integer          :: lda, i, j

    ptrNew = ptrOld + ((j-1) * lda + (i-1)) * sizeof_complex
end subroutine magmaf_coff2d

end module magma_cfortran
