!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!  This file is AUTOMATICALLY GENERATED by:
!!  ../tools/fortran_wrappers.pl ../include/magma_z.i
!!  Do not edit.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

module magma_zfortran

use magma_param

implicit none

!---- Fortran interfaces to MAGMA subroutines ----
interface

integer function magmaf_get_zpotrf_nb( m )
    integer :: m
end function magmaf_get_zpotrf_nb

integer function magmaf_get_zgetrf_nb( m )
    integer :: m
end function magmaf_get_zgetrf_nb

integer function magmaf_get_zgetri_nb( m )
    integer :: m
end function magmaf_get_zgetri_nb

integer function magmaf_get_zgeqrf_nb( m )
    integer :: m
end function magmaf_get_zgeqrf_nb

integer function magmaf_get_zgeqlf_nb( m )
    integer :: m
end function magmaf_get_zgeqlf_nb

integer function magmaf_get_zgehrd_nb( m )
    integer :: m
end function magmaf_get_zgehrd_nb

integer function magmaf_get_zhetrd_nb( m )
    integer :: m
end function magmaf_get_zhetrd_nb

integer function magmaf_get_zgelqf_nb( m )
    integer :: m
end function magmaf_get_zgelqf_nb

integer function magmaf_get_zgebrd_nb( m )
    integer :: m
end function magmaf_get_zgebrd_nb

integer function magmaf_get_zhegst_nb( m )
    integer :: m
end function magmaf_get_zhegst_nb

integer function magmaf_get_zgesvd_nb( m )
    integer :: m
end function magmaf_get_zgesvd_nb

subroutine magmaf_zgebrd( m, n, a, lda, d, e, tauq, taup, work, lwork, info, queue )
    integer          :: m
    integer          :: n
    complex*16       :: a(*)
    integer          :: lda
    double precision :: d(*)
    double precision :: e(*)
    complex*16       :: tauq(*)
    complex*16       :: taup(*)
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_zgebrd

subroutine magmaf_zgeqrf( m, n, A, lda, tau, work, lwork, info, queue )
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_zgeqrf

subroutine magmaf_zgesv( n, nrhs, A, lda, ipiv, B, ldb, info, queue )
    integer          :: n
    integer          :: nrhs
    complex*16       :: A(*)
    integer          :: lda
    integer          :: ipiv(*)
    complex*16       :: B(*)
    integer          :: ldb
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_zgesv

subroutine magmaf_zgetrf( m, n, A, lda, ipiv, info, queue )
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    integer          :: ipiv(*)
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_zgetrf

subroutine magmaf_zposv( uplo, n, nrhs, A, lda, B, ldb, info, queue )
    character        :: uplo
    integer          :: n
    integer          :: nrhs
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: B(*)
    integer          :: ldb
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_zposv

subroutine magmaf_zpotrf( uplo, n, A, lda, info, queue )
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    integer          :: info
    integer          :: queue(*)
end subroutine magmaf_zpotrf

subroutine magmaf_zunghr( n, ilo, ihi, a, lda, tau, dT, dT_offset, nb, info, queue )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    complex*16       :: a(*)
    integer          :: lda
    complex*16       :: tau(*)
    magma_devptr_t :: dT
    integer          :: dT_offset
    integer          :: nb
    integer          :: info
    integer          :: queue
end subroutine magmaf_zunghr

subroutine magmaf_zungqr( m, n, k, a, lda, tau, dT, dT_offset, nb, info, queue )
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: a(*)
    integer          :: lda
    complex*16       :: tau(*)
    magma_devptr_t :: dT
    integer          :: dT_offset
    integer          :: nb
    integer          :: info
    integer          :: queue
end subroutine magmaf_zungqr

subroutine magmaf_zunmtr( side, uplo, trans, m, n, a, lda, tau, c, ldc, work, lwork,  &
        info, queue )
    character        :: side
    character        :: uplo
    character        :: trans
    integer          :: m
    integer          :: n
    complex*16       :: a(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: c(*)
    integer          :: ldc
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_zunmtr

subroutine magmaf_zunmqr( side, trans, m, n, k, a, lda, tau, c, ldc, work, lwork, info,  &
        queue )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: a(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: c(*)
    integer          :: ldc
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_zunmqr

subroutine magmaf_zunmql( side, trans, m, n, k, a, lda, tau, c, ldc, work, lwork, info,  &
        queue )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: a(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: c(*)
    integer          :: ldc
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_zunmql

subroutine magmaf_zgeev( jobvl, jobvr, n, a, lda, geev_w_array, vl, ldvl, vr, ldvr, work,  &
        lwork, rwork, info, queue )
    character        :: jobvl
    character        :: jobvr
    integer          :: n
    complex*16       :: a(*)
    integer          :: lda
    complex*16       :: geev_w_array(*)
    complex*16       :: vl(*)
    integer          :: ldvl
    complex*16       :: vr(*)
    integer          :: ldvr
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: info
    integer          :: queue
end subroutine magmaf_zgeev

subroutine magmaf_zgesvd( jobu, jobvt, m, n, a, lda, s, u, ldu, vt, ldvt, work, lwork,  &
        rwork, info, queue )
    character        :: jobu
    character        :: jobvt
    integer          :: m
    integer          :: n
    complex*16       :: a(*)
    integer          :: lda
    double precision :: s(*)
    complex*16       :: u(*)
    integer          :: ldu
    complex*16       :: vt(*)
    integer          :: ldvt
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: info
    integer          :: queue
end subroutine magmaf_zgesvd

subroutine magmaf_zheevd( jobz, uplo, n, a, lda, w, work, lwork, rwork, lrwork, iwork,  &
        liwork, info, queue )
    character        :: jobz
    character        :: uplo
    integer          :: n
    complex*16       :: a(*)
    integer          :: lda
    double precision :: w(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_zheevd

subroutine magmaf_zstedx( range, n, vl, vu, il, iu, d, e, z, ldz, rwork, lrwork, iwork,  &
        liwork, dwork, info, queue )
    character        :: range
    integer          :: n
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    double precision :: d(*)
    double precision :: e(*)
    complex*16       :: z(*)
    integer          :: ldz
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    magma_devptr_t :: dwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_zstedx

subroutine magmaf_zgehrd( n, ilo, ihi, a, lda, tau, work, lwork, dT, dT_offset, info,  &
        queue )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    complex*16       :: a(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    magma_devptr_t :: dT
    integer          :: dT_offset
    integer          :: info
    integer          :: queue
end subroutine magmaf_zgehrd

subroutine magmaf_zhetrd( uplo, n, a, lda, d, e, tau, work, lwork, info, queue )
    character        :: uplo
    integer          :: n
    complex*16       :: a(*)
    integer          :: lda
    double precision :: d(*)
    double precision :: e(*)
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
    integer          :: queue
end subroutine magmaf_zhetrd

subroutine magmaf_zprint( m, n, A, lda )
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
end subroutine magmaf_zprint

end interface

!---- Fortran-only subroutines (see ../tools/fortran_wrappers.pl to edit) ----
contains

subroutine magmaf_zoff1d( ptrNew, ptrOld, inc, i)
    magma_devptr_t   :: ptrNew
    magma_devptr_t   :: ptrOld
    integer          :: inc, i

    ptrNew = ptrOld + (i-1) * inc * sizeof_complex_16
end subroutine magmaf_zoff1d

subroutine magmaf_zoff2d( ptrNew, ptrOld, lda, i, j)
    magma_devptr_t   :: ptrNew
    magma_devptr_t   :: ptrOld
    integer          :: lda, i, j

    ptrNew = ptrOld + ((j-1) * lda + (i-1)) * sizeof_complex_16
end subroutine magmaf_zoff2d

end module magma_zfortran
